export type PerpetualMarket = {
  coin: string;
  symbol: string;
  leverage: string | null;
  lastPrice: number | null;
  change24h: number | null;
  change24hPer: number | null;
  fundingPer: number | null;
  funding8hour: number | null;
  volume: number | null;
  openInterest: number | null;
  mark: number | null;
  oracle: number | null;
  volume24h: number | null;
  fundingDisplay: string | null;
  countdown: string | null;
  isFavorite: boolean;
};

export type MarketItem = {
  symbol: string;
  pair: string;
  iconLabel: string;
  iconBgColor: string;
  price: string;
  priceChange: string;
  changePercent: string;
  isPositive: boolean;
  leverage: string;
  mark: string;
  oracle: string;
  fundingPer: number | null;
  fundingDisplay: string;
  funding8hour: number | null;
  funding8hourDisplay: string;
  fundingCountdown: string;
  volume: string;
  volume24h: string;
  openInterest: string;
  isFavorite?: boolean;
};
